### ISSUE TITLE
User is registered as '--'

### ISSUE THREAD

**Issue by mvdpoel** [jarektkaczyk/revisionable#1]
Hey,

First of all, thx for this package!

I got it almost working in my application, the only thing it doesn't do is record the user that made the change. I'm using the default Illuminate Auth provider, but that gives me an integer of the user ID. Which is being ignored and results in the '--'. 

Actually, i would like to save the user ID in stead of the name, could you help me out to get that working?

By the way, i'm using tag 0.1.6.

Hope to hear from you,

Kind regards,

Martin

**Comment by jarektkaczyk** [comment]
I will look into it soon.

**Comment by jarektkaczyk** [comment]
It's been solved. You can provide a string or numeric value like id. Use `v0.2`
