### ISSUE TITLE
History not maintained in revisions table

### ISSUE THREAD

**Issue by arvind132** [jarektkaczyk/revisionable#11]
Hi, I am using laravel 4.2 i have done all the steps that you have mentioned, when i update a record through model it is not updating in the revisions table. i dont know what i have to do make it work.

**Comment by jarektkaczyk** [comment]
1. which version of the package did you use?
2. provide the relevant code - the best if you just create a repo with the relevant models config etc.

**Comment by arvind132** [comment]
Package version: sofa/revisionable": "~0.2@dev

This is my model 

<?php
use Sofa\Revisionable\Laravel\RevisionableTrait;

class User extends Eloquent {

```
use RevisionableTrait;

// Set revisionable whitelist - only changes to any
// of these fields will be tracked during updates.
protected $revisionable = [
    'email'
];

// Or revisionable blacklist - if $revisionable is not set
// then you can exclude some fields from being tracked.
protected $nonRevisionable = [
    'created_at',
    'updated_at',
];
```

}

**Comment by jarektkaczyk** [comment]
Did you make sure, that all the steps were correct?
1. added Service Provider
2. published the config
3. ran the migration

And the model you're using is for sure the one you showed?
Do you use different connections or just one, default for all db operations?

If so, then pls, create a repo with the code, otherwise it will be impossible to find the problem or reproduce it.

**Comment by arvind132** [comment]
I have done all the steps that you have mentioned, only one connections i have used for all the db operations. could you please show me an example code for a model? it may clear my doubts.

**Comment by jarektkaczyk** [comment]
This is real 4.2 model:

```
...
use Sofa\Revisionable\Laravel\RevisionableTrait;

class User extends Model implements UserInterface, RemindableInterface {

    use UserTrait, RemindableTrait, SoftDeletingTrait;
    use RevisionableTrait;

    protected $revisionable = [
        'email',
        'name',
        ...
    ];

```

Show me the code that you execute, which should trigger the revision.

**Comment by arvind132** [comment]
Route::get("update",function(){
    User::where("id",'1')->update(array('email'=>'asdsad@ueasdwefq.com'));
    echo "success";
});

This is how i have execute update command from my routes.php in laravel and then here comes my model

use Sofa\Revisionable\Laravel\RevisionableTrait;

class User extends Eloquent {
    use RevisionableTrait;
    // Set revisionable whitelist - only changes to any
    // of these fields will be tracked during updates.
    protected $revisionable = [
        'email'
    ];

```
// Or revisionable blacklist - if $revisionable is not set
// then you can exclude some fields from being tracked.
protected $nonRevisionable = [
    'created_at',
    'updated_at',
];
```

Whatever the update i have executed it gets affected in the users table and revisions table still remains empty it should save the version before its get updated, it not working for me could please tell me where i had a mistake  or is there anything else needs to be configured.

Thanks in advance.

**Comment by jarektkaczyk** [comment]
@arvind132 This is not the AR way of handling updates. You're calling `update` directly on the query, which is not triggering `updating` event for any model.

Instead do this:

```
$user = User::find(1);
$user->update( ... your data here ... ); // event fired, revision saved
```

**Comment by arvind132** [comment]
Thank you now its working, thanks a lot
