### ISSUE TITLE
Is this packages supportable for laravel 4.0

### ISSUE THREAD

**Issue by arvind132** [jarektkaczyk/revisionable#12]
When i tried this package with laravel 4.0 i got this error when i was going to publish the config

$ php artisan config:publish sofa/revisionable
{"error":{"type":"Symfony\Component\Debug\Exception\FatalErrorException","me
ssage":"Call to undefined method Illuminate\Foundation\Application::bindShared
()"
)

is there any way to resolve it, because i desperately need this package.

**Comment by jarektkaczyk** [comment]
Nope, it's PHP5.4+ and L4.2+.
