### ISSUE TITLE
Pushing up version number

### ISSUE THREAD

**Issue by Omranic** [jarektkaczyk/revisionable#15]
Hello Dear Jarek,

First of all thank you for this piece of art package, it really helped much in our projects.

This isn't an issue, just asking you to push up the version number so the latest updates could be fetched from the composer since it still sees old versions 1.0.1/0.2.2 which already cached on packagist & locally.
Again, thank you for your hard work, keep up the good work +1

Sincerely Regards
Abdelrahman Omran

**Comment by jarektkaczyk** [comment]
done, thx
