### ISSUE TITLE
Differences between branches master and 1.0

### ISSUE THREAD

**Issue by carlosviol** [jarektkaczyk/revisionable#19]
Hello Jarek, how are you?

It's not exactly an issue, I think, but I'm confused about this. I have a question about actual branches (master and 1.0).

Recently I'd asked you about L4.2 and L5 support, and L4.2 is just in dev-master (packagist). I saw that 1.0 has for example "Presenter->labels", that not exists in dev-master.

What the logic of these branches, and how do you plan to continue with these?

Currently I need the "labels" and "passThrough" but I'm using dev-master because we use L4.2 here.

Thank you very much for your work, it help us a lot here! :+1: As I said, I intend to continue helping you with this project, always as I can.

Regards,
Carlos

**Comment by jarektkaczyk** [comment]
@carlosviol Hey there, you're right it's unclear in fact.

The thing is, `dev-master` branch is 0.2, while new, improved version is in 1.x branch. I didn't fix it, in case of situation like yours - so nobody using `master` gets new, L5 version with `composer update`. That said, currently I don't intend to change this.

**Comment by carlosviol** [comment]
@jarektkaczyk So what do you think to I have to do? Try to merge master (L4.2) in 1.0? Try to merge just my need, of labels, for example? I think it's better to stay with both compatibility in one branch, what do you think about?

Thanks again!
