### ISSUE TITLE
False returned by listener stops propogation of the event to other listeners.

### ISSUE THREAD

**Issue by dexmans** [jarektkaczyk/revisionable#2]
Ran into this issue while disabling the revisions on one model with `$this->disableRevisioning()`, which had other listeners attached to it by another trait.

The on[Event] methods in `revisionable/src/Laravel/Listener.php` will return the result of the `$this->log()` method. When this returns false (in the case of `$this->disableRevisioning()`), laravel will not propogate the event to other listeners. Also `onUpdated()` does the same when there's no diff.

**Comment by jarektkaczyk** [comment]
@dexmans Thanks. I'm not even sure now why I changed them to return `false` ;) Anyway you're right of course, fixed already `@dev`.
