### ISSUE TITLE
Migration - The use statement with non-compound name 'Config' has no effect  

### ISSUE THREAD

**Issue by dominiquedutra** [jarektkaczyk/revisionable#23]
Hi there,

Got this ErrorException when trying to do a php artisan migrate.

I removed the use Config; on top of the migration file and the migration worked just fine.

laravel/framework": "5.0.*

Not sure if its a issue or is just a thing on my side.

Thanks.

**Comment by jarektkaczyk** [comment]
Which version exactly?

It's fixed now.

**Comment by dominiquedutra** [comment]
Version 1.0

Thank you very much.

**Comment by zahirkelloud** [comment]
I'm having the same issue. My app was natively developed using Laravel 4.2 when I switched to Laravel 5.1. I commented out the lines that I've had issue with and it worked fine but I don't know if it's the right thing to do.
