### ISSUE TITLE
Not tracking revisions under these circunstances

### ISSUE THREAD

**Issue by dominiquedutra** [jarektkaczyk/revisionable#24]
Hello,

Revisionable is 1.0.
Laravel is 5.0.

I noticed that under these circunstances the revisions are not tracked.

When instead of extending Eloquent, I extend Illuminate\Database\Eloquent\Model directly, which is the same (?). Like so:

```
<?php namespace App\Models;

/**
 * Changes to this model generate a revision entry.
 */
use Sofa\Revisionable\Laravel\RevisionableTrait;
use Sofa\Revisionable\Revisionable;
use Illuminate\Database\Eloquent\Model;


class Representante extends Model implements Revisionable {

  use RevisionableTrait;

  protected $fillable = ['nome', 'telefone', 'email'];
  protected $revisionable = ['nome', 'telefone', 'email'];


  public function clientes()
  {
    return $this->hasMany('App\Models\Cliente');
  }

}
```

Or when extending a BaseModel, like so:

```
<?php namespace App\Models;

use Eloquent;
use \Carbon\Carbon;

/**
 * Our base model
 */
class BaseModel extends Eloquent {

  function __construct() {
    Carbon::setLocale('pt_BR');
    Carbon::setToStringFormat('d/m/Y H:i:s');
  }  

}
```

```
<?php namespace App\Models;

use Sofa\Revisionable\Laravel\RevisionableTrait;
use Sofa\Revisionable\Revisionable;

class Representante extends BaseModel implements Revisionable {

  use RevisionableTrait;

  protected $fillable = ['nome', 'telefone', 'email'];
  protected $revisionable = ['nome', 'telefone', 'email'];


  public function clientes()
  {
    return $this->hasMany('App\Models\Cliente');
  }

}
```

It only works if I extend Eloquent directly on the revisionable model class, which doesnt allow me to use a BaseModel. Is there any reason for this that I am not seeing?

Like this, it works perfectly:

```
<?php namespace App\Models;

use Eloquent;
use Sofa\Revisionable\Laravel\RevisionableTrait;
use Sofa\Revisionable\Revisionable;

class Representante extends Eloquent implements Revisionable {

  use RevisionableTrait;

  protected $fillable = ['nome', 'telefone', 'email'];
  protected $revisionable = ['nome', 'telefone', 'email'];


  public function clientes()
  {
    return $this->hasMany('App\Models\Cliente');
  }

}
```

Best regards.

**Comment by jarektkaczyk** [comment]
@dominiquedutra Hey.

Here you go:
1. No way that it doesn't work b/c you extend `Model` instead of `Eloquent` - I personally never ever use the `Eloquent` alias for my models. 
2. Your `BaseModel` looks bad - it overrides constructor without calling `Model` constructor, which will cause problems. 

If this is whole code you have in these classes, then nothing wrong here.

Make sure everything in the model is OK and that revisionable fields are `dirty`.

**Comment by dominiquedutra** [comment]
@jarektkaczyk 
You are absolutely right, thanks for your time.

Problem was my base model overwriting __construct() on parent. I took a quick look at the abstract model class and saw no construct on top and assumed, well it was stupid.

Just a rookie mistake.

Anyways, it works just fine I can format carbon dates, write my common model functions on my BaseModel and extends it on a Model class that implements Revisionable.

Works like a charm.

Thanks!
