### ISSUE TITLE
Update event doesn't fire with Http (Created, Deleted & Restored work fine)

### ISSUE THREAD

**Issue by AppSynergy** [jarektkaczyk/revisionable#28]
I'm using Laravel 5.0, composer resolves to `1.0.x-dev`.

Other three events all behave as I'd expect, and the old/new/diff shows I've got the `protected $revisionable` fields right..

The event seems to be registered:

``` php
use Clientname\Models\User

User::getRevisionableEvents()
=> [
       "Created",
       "Updated",
       "Deleted",
       "Restored"
   ]
```

I did some debugging in `Laravel/Listener.php`  ( `print(__FUNCTION__);`) and found:

``` php
>>> $u = User::find(151);
>>> $u->delete();
__constructonDeleted⏎  // as expected
=> true
>>> $u->delete();
=> null   // as expected, no action when you delete the already-deleted!
>>> $u->restore()
__constructonUpdated__constructonRestored⏎  // should both be here?
=> true
>>> $u->update(['name' => 'Bill Foo']);
__constructonUpdated⏎ // ok, great
=> true
```

and the update command **does** fire if I do it like that via the Tinker CLI.

So why doesn't it fire for my Http Requests? The other three events do.

``` php
// controller method
public function update(UserRepository $user, EditUserRequest $request, $id)
    {
        // ....
        $user->update($request->only($fields), $id);
        // ....
    }

// repository method
public function update(array $data, $id, $attribute = 'id') {
        // ...
        return $this->model->withTrashed()->where($attribute, '=', $id)->update($data);
    }
```

Ideas appreciated!

**Comment by AppSynergy** [comment]
Ok, I found [this](https://github.com/jarektkaczyk/revisionable/blob/1.0/spec/Sofa/Revisionable/Laravel/ListenerSpec.php#L26) so this is clearly on-spec behavior. 

I guess it's counter-intuitive though, as `Builder` also has an update method which achieves the same thing (afaik?) 

FIx for my code:

``` php
->where($attribute, '=', $id)->first()->update($data);
// first() resolves query builder to an Eloquent model.
```

**Comment by jarektkaczyk** [comment]
@AppSynergy Being it dependable on the eloquent events, unfortunately you can't rely on `Builder's` update method. In Eloquent there's difference between:

```
Model::where(..)->update()
// and
$model->update()
```

First is called on the builder and **doesn't fire any event**.

**Comment by AppSynergy** [comment]
I get it now, thanks. I couldn't see quite how the events got attached, but now I see it's this:

http://laravel.com/docs/5.0/eloquent#model-events
