### ISSUE TITLE
Display Revisions

### ISSUE THREAD

**Issue by nathangoss** [jarektkaczyk/revisionable#3]
Hi there,

Thanks for this great framework! I have it logging revisions successfully which has saved me a lot of time.

With regards to retrieving the revisions for a particular model, do you have an example on how to do that?

Here is an example of how to do it in VentureCraft/revisionable:

``` PHP
@foreach($account->revisionHistory as $history )
    <li>{{ $history->userResponsible()->first_name }} changed {{ $history->fieldName() }} from {{ $history->oldValue() }} to {{ $history->newValue() }}</li>
@endforeach
```

Thanks,

Nathan

**Comment by jarektkaczyk** [comment]
There are a few options. 

### Use the `Presenter` then this is all you need:

```
$revisions = DB::table('revisions')->orderBy('revisions.created_at', 'desc')->get();

$revisions = array_map(function ($revision) {
    return App::make('Sofa\Revisionable\Presenter', [(array) $revision]);
}, $revisions);

return $this->view->make('some.view', compact('revisions'));


// the view
@foreach($revisions as $revision)
    <tr>
        <td class="revision-timestamp">{{ $revision->created_at }}</td>
        <td class="revision-type">{{ $revision->type }}</td>
        <td class="revision-table_name">{{ $revision->table_name }}</td>
        <td class="revision-row_id">{{ $revision->row_id }}</td>
        <td class="revision-diff"> {{ $revision->renderDiff() }} </td>
        <td class="revision-user">{{ $revision->user_name }}</td>
        <td class="revision-ip">{{ whois_link($revision->ip) }}</td>
    </tr>
@endforeach
```

to get something like this (there is additional user name, ignore it):

![image](https://cloud.githubusercontent.com/assets/6928818/6411544/ec10125a-be79-11e4-86a2-b477a2e9ac18.png)

### Also you can do what you asked about (example from the other package):

```
// for example like this:
$revisions = $account->revisions->map(function ($revision) {
  return App::make('Sofa\Revisionable\Presenter', [$revision]); 
});

@foreach ($revisions as $revision )
  @foreach ($revision->getUpdated() as $field) // all updated field 
    <li>{{ $revision->user }} changed {{ $field }} from {{ $revision->old($field) }} to {{ $revision->new($field) }}</li>
  @endforeach
@endforeach


// or for specified $field that you want:
@foreach ($revisions as $revision ) @if (in_array($field, $revision->getUpdated()))
    <li>On {{$revision->created_at}} user {{ $revision->user }} changed {{ $field }} from {{ $revision->old($field) }} to {{ $revision->new($field) }}</li>
@endif @endforeach
```

**Comment by infinite-sea** [comment]
Can't seem to get the Presenter example to work, keep getting Class Sofa\Revisionable\Presenter does not exist

Any ideas ?

**Comment by jarektkaczyk** [comment]
@infinite-sea `Sofa\Revisionable\Laravel\Presenter`

**Comment by infinite-sea** [comment]
Tried that, as that looked like the path, but that give a new error - Target [Illuminate\Database\Eloquent\Model] is not instantiable.

**Comment by jarektkaczyk** [comment]
Show the code then

**Comment by infinite-sea** [comment]
```
    $revisions = \DB::table('revisions')->orderBy('revisions.created_at', 'desc')->get();

    $revisions = array_map(function ($revision) {
        return \App::make('Sofa\Revisionable\Laravel\Presenter', [(array) $revision]);
    }, $revisions);

    return view('revisions.index', compact('revisions'));
```

Everything is setup like the example, and works as far as tracking the changes, just trying to use the above to display. 

BindingResolutionException in Container.php line 785:
Target [Illuminate\Database\Eloquent\Model] is not instantiable.

**Comment by jarektkaczyk** [comment]
@infinite-sea This example is outdated. It's easier now, just define presenter class and things will happen automatically. Read this https://github.com/jarektkaczyk/revisionable#customization-in-l5

**Comment by infinite-sea** [comment]
Thanks, sorry for the trouble.

**Comment by infinite-sea** [comment]
Last question - I have been trying to find out how to display User info , but cannot see how to do this. $revision->user  is this integer of the user id . Do I need to look it up, or create a Revision model to belongTo a User ? Or is there some magic in the RevisionableTrait that provides the User relationship?

**Comment by jarektkaczyk** [comment]
No, it doesn't automatically gets the user. You may create the relation or join users table. I prefer logging only user's email and showing it without fetching the user, that's why it works this way.

**Comment by infinite-sea** [comment]
Ok, cool. Thanks again !

**Comment by Apoculos** [comment]
Hi jarektkaczyk, great package!

 I'm trying to display all revisions in my table with the differences for all tables being displayed. I'm having a hard time understanding how to do that. Do I need to setup a presenter class for every model? 

Everything is being tracked correctly and I'm able to output all the data to a datatable(using yajra/laravel-datatables), but I'm not sure how to render the difference in a single column like I see in a screenshot you posted. Below is what I have now.. I would like to display differences instead of long strings of Old and New json arrays. Appreciate any direction you can offer..

![image](https://cloud.githubusercontent.com/assets/11741410/8045179/4058f5ee-0df7-11e5-8b08-40aa19dbb02e.png)
