### ISSUE TITLE
Error: latestRevision is Undefined Property

### ISSUE THREAD

**Issue by nikhileshva** [jarektkaczyk/revisionable#30]
When I run this: 
$ticket = App\Tickets::where('ticket_id', '=', 14)->get();

and then: 
$revision = $ticket->latestRevision;

I get this error: 
PHP error:  Undefined property: Illuminate\Database\Eloquent\Collection::$latestRevision on line 1

What is wrong with my approach?

**Comment by jarektkaczyk** [comment]
@BlazeNikhilesh `get` and `find/first` return different things. You basically are trying to get single model's property on the collection of models.

That said: `$ticket = App\Ticket::where(..)->first()` and btw I suggest singular name for the model, but that's up to you.
