### ISSUE TITLE
The revisions table only saves the created entry

### ISSUE THREAD

**Issue by nikhileshva** [jarektkaczyk/revisionable#31]
I set up revisions on a model Tickets

<pre>
use Sofa\Revisionable\Revisionable;
use Sofa\Revisionable\Laravel\RevisionableTrait;

class Tickets extends Model implements Revisionable  {

    use RevisionableTrait;
        protected $revisionable = array(
        'stage_id',
        'assigned_to',
        'updated_at',
    );
</pre>

But, any revisions on this table are not stored in revisions table. Only the newly created entry are stored. When I update stage_id, nothing is stored in revisions table.

**Comment by jarektkaczyk** [comment]
@BlazeNikhilesh Show the relevant code updating your model.

**Comment by nikhileshva** [comment]
I was able to solve this problem with Issue #28 .
