### ISSUE TITLE
Presenters not working

### ISSUE THREAD

**Issue by nikhileshva** [jarektkaczyk/revisionable#32]
First I find a ticket. 

<pre>
$tick = App\Tickets::find(14);
</pre>

Then I find a revision for the same: 

<pre>
$rev = $tick->latestRevision;
</pre>

But it gives me a error:

<pre>
App\Presenters\Revisions\Tickets #0000000021ba4aef0000000179e23051 {}
</pre>

When I see in database, the revisions table is updated with a revision.

And this is my Presenters code:

<pre>
namespace App\Presenters\Revisions;

use Sofa\Revisionable\Laravel\Presenter;

class Tickets extends Presenter {

protected $passThrough = [
        'stage_id'        => 'ticket_stages.stage_name',
        'assigned_to'    => 'users_details.user_name',
    ];
protected $actions = [
        'created'  => 'Created at',
        'updated'  => 'Updated at',
        'deleted'  => 'Deleted',
        'restored' => 'Restored',
    ];
}
</pre>

**Comment by jarektkaczyk** [comment]
@BlazeNikhilesh You didn't get (or at least show) any error.

Btw is `ticket_stages.stage_name` relation call really? You shouldn't be referencing `table.column`, but `relation.attribute` there.

**Comment by nikhileshva** [comment]
And where does this relation and attribute come from?

**Comment by nikhileshva** [comment]
So this is my relation from Tickets model. 

<pre>
public function stage() {
        return $this->hasOne('App\Stages');
    }
</pre>

And I used stage.stage_name in passThrough, but still there is no result.
