### ISSUE TITLE
How to get the 'Name' of user from the revisions table?

### ISSUE THREAD

**Issue by nikhileshva** [jarektkaczyk/revisionable#33]
<pre>
$ticket = App\Tickets::find(14);
</pre>

<pre>
$revisions = $ticket->latestRevision;
</pre>

How do I get the details of the user who is responsible for this revision. I see that in revision table, column user stores the user_id. How do I get it from the $revisions variable??

**Comment by jarektkaczyk** [comment]
@BlazeNikhilesh You can make revisionable save any field from the user's table - check the `config` part of the docs. The idea is that it doesn't depend on the relations, but static fields, so there's no eloquent relationship defined.

Otherwise you need to manually join user's table.
