### ISSUE TITLE
I am able to get the latestRevision, but not able to get all the revision

### ISSUE THREAD

**Issue by nikhileshva** [jarektkaczyk/revisionable#34]
There's a way to get the latest revision on a ticket, but how can I get all the revision on a ticket.

$tickets = Tickets::find($id);
$revision = $tickets->latestRevision

How can I get all the revisions on this particular ticket??

**Comment by jbellomy** [comment]
@BlazeNikhilesh To get all revisions you would do the following:

$tickets = Tickets::find($id);
$revisions = $tickets->revisions()->get();
