### ISSUE TITLE
Not able to get the Labels from presenters

### ISSUE THREAD

**Issue by nikhileshva** [jarektkaczyk/revisionable#35]
I have this Labels array in presenters file: 

<pre>
protected $labels = [
        'stage_id'      => 'Changed Ticket Stage From',
        'assigned_to'   => 'Assigned Ticket From',
];
</pre>

I am trying to get the labels for 'stage_id'

<pre>
$ticket = Tickets::find($id);
$revisions = $ticket->revisions()->get();
print_r($revisions[0]->label('stage_id'));
</pre>

but, this only prints 'stage_id', and not the string that I need.

What could be the issue with this?

**Comment by jarektkaczyk** [comment]
Have you solved it already?

**Comment by nikhileshva** [comment]
No, this is not solved yet.
