### ISSUE TITLE
Get revisions of a sub-object

### ISSUE THREAD

**Issue by Fl0ux** [jarektkaczyk/revisionable#37]
It seems to be impossible to get revisions of a sub-object using directly revisionable.

Example : 
Contact object has many Phone objects. A phone is deleted. Then I have no way to retrieve revisions of this object using the Contact object.

I think this could be a great feature to add !

Many thanks for this package btw !

**Comment by hasokeric** [comment]
I agree this would be awesome... right now i am just tracking all the sub-objects as well.
