### ISSUE TITLE
Ambiguous class resolution warning

### ISSUE THREAD

**Issue by rjp2525** [jarektkaczyk/revisionable#38]
Each time I run a composer command, I always get this warning with this particular package:

```
Warning: Ambiguous class resolution, "CreateSofaRevisionsTable" was found in both "$baseDir . '/database/migrations/2015_03_05_000000_create_sofa_revisions_table.php" and "/home/dev/vendor/sofa/revisionable/src/migrations/2015_03_05_000000_create_sofa_revisions_table.php", the first will be used.
```

It's not overly important since it's loading the correct one, but still should be fixed so a warning doesn't pop up every time I run a composer command.

**Comment by jarektkaczyk** [comment]
It will be resolved once the commands are implemented.

**Comment by aedart** [comment]
Actually, all you have to do, is to move your `classmap` (src/migrations) from the `autoload`, and into the your `autoload-dev`. Then this issue will not longer be present in the top-level application, that depends on this package
