### ISSUE TITLE
Update is not being tracked

### ISSUE THREAD

**Issue by hasokeric** [jarektkaczyk/revisionable#42]
What would the reason be for a Update not to be tracked... Creating works just fine however

```
     App\Article::where('id', 1)
          ->update(['author' => "Some New Author"]);
```

does nothing.

**Comment by jarektkaczyk** [comment]
@hasokeric You work on the query, not the model, so it can't - see this https://github.com/jarektkaczyk/revisionable/issues/28#issuecomment-107830522
