### ISSUE TITLE
Bug when relying simply just on latest()

### ISSUE THREAD

**Issue by hasokeric** [jarektkaczyk/revisionable#43]
If you do a create and then shortly after a delete or an update the created_at timestamp will be the same therfore

```
    public function latestRevision()
    {
        return $this->hasOne('Sofa\Revisionable\Laravel\Revision', 'row_id')
            ->where('table_name', $this->getTable())
            ->latest();
    }
```

using simply latest() will yield incorrect results... i think it should sort by created_at and also the id.

**Comment by hasokeric** [comment]
Fix would be 

```
    public function latestRevision()
    {
        return $this->hasOne('Sofa\Revisionable\Laravel\Revision', 'row_id')
            ->where('table_name', $this->getTable())
            ->latest()->orderBy('id', 'desc');
    }
```

**Comment by jarektkaczyk** [comment]
@hasokeric What would be real use-case of such action?

**Comment by hasokeric** [comment]
Well i am importing lets say January.csv and February.csv and January would do a 'create' revision and then February would add an 'update' revision and it would show January as the latest revision.

In addition sometimes you do have to do 

```
$model->some_column = true;
$model->save();

and then once that it saved you change or add a second column further down in code

$model->here_i_am_again = "test";
$model->save();
```

the timestamps would be if this executes quick the same once again latest() is sorting by 'created_at' and would yield the incorrect lastRevision().

Thoughts?

**Comment by iWader** [comment]
The only issue with sorting based on the primary key is what if you're not using an incremental value such as UUIDs?
