### ISSUE TITLE
Revisionable not saving changes on Laravel 5.1

### ISSUE THREAD

**Issue by tochie-daniels** [jarektkaczyk/revisionable#47]
Hi, I cant seem to get Revisionable to save changes. Here's my model:

namespace App\Models\v1\; 
use Illuminate\Database\Eloquent\Model;
use Sofa\Revisionable\Laravel\RevisionableTrait;
use Sofa\Revisionable\Revisionable;
class Company extends Model implements Revisionable
{
    use RevisionableTrait;
}
1. The model does not throw any errors. Changes are not saved to the revisions db table. 
2. Also I noticed that Laravel stopped using Eloquent, but this package still extends /Eloquent. Why is this?

Any ideas please?

**Comment by tochie-daniels** [comment]
Any help from someone please?

**Comment by hasokeric** [comment]
That is odd; i can confirm that it works in 5.2 as of today - my Class setup looks exactly like yours

```
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Sofa\Revisionable\Revisionable;
use Sofa\Revisionable\Laravel\RevisionableTrait;

class User extends Authenticatable implements Revisionable
{

    use RevisionableTrait;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'role',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}
```
