### ISSUE TITLE
[Laravel 5.2.x] bindShared() is deprecated, use singleton instead, in ServiceProvider

### ISSUE THREAD

**Issue by aedart** [jarektkaczyk/revisionable#48]
At the moment, `\Sofa\Revisionable\Laravel\ServiceProvider` cannot be used with Laravel 5.2.x, because of usage of the `bindShared` method.

According to the documentation (https://laravel.com/docs/5.2/upgrade#upgrade-5.2.0), that method should be replaced with the `singleton` method.

Can you please create a hotfix, asap?

**Comment by L1lle** [comment]
@aedart  There is already a hotfix and pull request for this issue see https://github.com/jarektkaczyk/revisionable/pull/46 .

@jarektkaczyk But please add 5.2 support/the pull request because the continuous deployment server can not work with that hotfix.
