### ISSUE TITLE
 php artisan vendor:publish error

### ISSUE THREAD

**Issue by paramsinghvc** [jarektkaczyk/revisionable#5]
$ php artisan vendor:publish --provider="Sofa\Revisionable\Laravel\FiveServiceProvider"
PHP Fatal error:  Call to undefined method Sofa\Revisionable\Laravel\FiveServiceProvider::publishes() in /Users/param/Documents/code/LookManagerApi/vendor/sofa/revisionable/src/Laravel/FiveServiceProvider.php on line 25
{"error":{"type":"Symfony\Component\Debug\Exception\FatalErrorException","message":"Call to undefined method Sofa\Revisionable\Laravel\FiveServiceProvider::publishes()","file":"\/Users\/param\/Documents\/code\/LookManagerApi\/vendor\/sofa\/revisionable\/src\/Laravel\/FiveServiceProvider.php","line":25}}

**Comment by jarektkaczyk** [comment]
@paramsinghvc Which version (exactly) of the framework?

**Comment by paramsinghvc** [comment]
Laravel 4.2 . I don't wanna upgrade to Laravel 5. Isn't there a way to get it working with 4.2

**Comment by paramsinghvc** [comment]
Never mind. I followed the wrong guide for Laravel 4.
