### ISSUE TITLE
different database connection

### ISSUE THREAD

**Issue by ronnievisser** [jarektkaczyk/revisionable#55]
Hi,

my revisions table is on a different db connection then the default. How can I set the connection on the Revision model? I don't see any option in the config for that.

**Comment by sbtsdev** [comment]
RonnieVisser,
I had a similar problem, and I found I had to change the package code of revisionable to get it to work.  You can see an example of what I changed [here](https://github.com/sbtsdev/revisionable/commit/cf03e40a8b37684230957ff8b6026cbb0044dde5).
I'm not sure why my pull request was closed.  I was looking into why when I saw your post.

**Comment by sbtsdev** [comment]
RonnieVisser,
Make sure you are looking at the [2.0 version](https://github.com/jarektkaczyk/revisionable/tree/2.0) of the package.  I think if you upgrade to that then you will have the database connection option in the config file that we are both wanting.

**Comment by ronnievisser** [comment]
The Revision model isn't using the collection config setting so it still isn't working for me.

**Comment by jarektkaczyk** [comment]
@RonnieVisser Show the code so I can reproduce that. Everything seems to be fine.

**Comment by ronnievisser** [comment]
What do you want me to share? I was looking at the Revision model which does not have a connection property.

Also I'm still getting the same error that table could not be found!

Regards, Ronnie
