### ISSUE TITLE
publishing config failes

### ISSUE THREAD

**Issue by ronnievisser** [jarektkaczyk/revisionable#56]
the following error occurs:

  [Symfony\Component\Debug\Exception\FatalThrowableError]  
  Type error: Argument 2 passed to Sofa\Revisionable\Laravel\RevisionsTableCo  
  mmand::__construct() must be an instance of Illuminate\Foundation\Composer,  
   instance of Illuminate\Support\Composer given, called in /home/vagrant/Cod  
  e/Personal/PHP/Application/Web/vendor/sofa/revisionable/src/Laravel/ServicePr  
  ovider.php on line 143

**Comment by jarektkaczyk** [comment]
Which version of package and framework (exactly)?

**Comment by ronnievisser** [comment]
Version 2.0 and laravel 5.2

I have added the service provider and then i run php artisan vendor:publish [--provider="Sofa\Revisionable\Laravel\ServiceProvider"]

Regards, Ronnie

**Comment by dazzcreations** [comment]
Same response when using Laravel 5.3

**Comment by ronnievisser** [comment]
is this something that is going to be fixed?

the following error is being thrown in 5.3

  [Symfony\Component\Debug\Exception\FatalThrowableError]  
  Type error: Argument 2 passed to Sofa\Revisionable\Laravel\RevisionsTableCo  
  mmand::__construct() must be an instance of Illuminate\Foundation\Composer,  
   instance of Illuminate\Support\Composer given, called in /home/vagrant/Cod  
  e/Personal/PHP/Soccerama/Live/vendor/sofa/revisionable/src/Laravel/ServiceP  
  rovider.php on line 144

**Comment by jarektkaczyk** [comment]
It has been fixed in September: https://github.com/jarektkaczyk/revisionable/blob/v5.3.2/src/Laravel/RevisionsTableCommand.php#L6

and working fine on my end on L5.3 + R5.3.

Make sure to update dependencies.

**Comment by jarektkaczyk** [comment]
Fixed on branch 2.0 as well https://github.com/jarektkaczyk/revisionable/releases/tag/v2.0.5

**Comment by ronnievisser** [comment]
What branche should be we use? I need it to work on a different database connection. Is 2.0 suitable for this or should we use 5.3?

Gr, Ronnie

**Comment by jarektkaczyk** [comment]
@ronnievisser depends on your Laravel installation. This package follows Laravel version since 5.2.

2.\* branch is suitable for L5.0/5.1
