### ISSUE TITLE
How to trigger a revision for a custom method from a Controller?

### ISSUE THREAD

**Issue by franciscocorrales** [jarektkaczyk/revisionable#58]
Idea: log an action, that is not neither Create/Update/Delete.

I posted [a question](http://stackoverflow.com/questions/39644878/) on StackOverflow related to this idea.

Example:
An user sends an email (this action doesn't CRUD any model), but I want to track this action. So I do something like:
`Action::make('send email', $user, $email, $time, $from, $to, $subject, ....)`

So, can this be done with this package ?

**Comment by jarektkaczyk** [comment]
Ola!
I was on holiday last week.
Have you got it working already? This package provides an easy and fast way of CRUD-related log. For what you ask for, I would suggest custom handler or packages like the one you mentioned - https://github.com/spatie/laravel-activitylog

**Comment by franciscocorrales** [comment]
Hi,

I ended up doing it with [that logger](https://github.com/spatie/laravel-activitylog). It works pretty good. I just wanted to know if the same functionality could be handled someway with this package.

Thanks.
