### ISSUE TITLE
Polymorphic laravel relations revisions

### ISSUE THREAD

**Issue by paramsinghvc** [jarektkaczyk/revisionable#6]
I want to track the relations existing between my models say a Product has many tags and a tag may belong to many products. How can achieve that which says "this tag has been removed from this product".

**Comment by jarektkaczyk** [comment]
Eloquent doesn't provide any events for relations, so you have to take care of this by yourself.

**Comment by paramsinghvc** [comment]
Jst need a hint. Do I need to apply revisionable trait on the pivot to achieve this thing?

**Comment by jarektkaczyk** [comment]
Nope, you can't do that without firing events by yourself. Eloquent m-m relations don't use Pivot model when `syncing / attaching / detaching` - it's just a query on the pivot table.

I'm working on the events for this case right now, so maybe it will be in the package in a few days as well. Meanwhile read this to get you started: http://stackoverflow.com/questions/28925292/eloquent-attach-detach-sync-fires-any-event/28934080#28934080
