### ISSUE TITLE
Getting exception while publishing vendor files.

### ISSUE THREAD

**Issue by zibzobzub** [jarektkaczyk/revisionable#60]
Here's the screenshot I'm getting while excuting 

`php artisan vendor:publish --provider="Sofa\Revisionable\Laravel\ServiceProvider"`

![image](https://cloud.githubusercontent.com/assets/10152692/20417866/7092c870-ad83-11e6-8624-7a10faa83d8a.png)

Using `composer require sofa/revisionable ~2.0` as per Readme.md on branch 5.3

Anyway after playing around, I have tried `composer require sofa/revisionable` which downloads branch 5.3 and the `artisan vendor:publish` command works fine but I'm confused which branch should I use, since on branch 5.3 the Readme.md state to use 2.0 branch.

**Comment by jarektkaczyk** [comment]
fixed readme - for L5.3 you use 5.3 of revisionable.
