### ISSUE TITLE
Class 'Sofa\Revisionable\Adapters\SessionProvider' not found

### ISSUE THREAD

**Issue by the91end** [jarektkaczyk/revisionable#62]
I got this error for version 5.3.3 on Laravel 5.3

`Class 'Sofa\Revisionable\Adapters\SessionProvider' not found`

The problem is the adapter's class name is `Session`, not `SessionProvider`

**Comment by jarektkaczyk** [comment]
fixed in https://github.com/jarektkaczyk/revisionable/releases/tag/v5.3.4
