### ISSUE TITLE
Call to undefined method Sofa\Revisionable\Laravel\ServiceProvider::publishes()

### ISSUE THREAD

**Issue by neoacevedo** [jarektkaczyk/revisionable#64]
Hi, when I try to run the command `php artisan revisions:table` I get 

> Call to undefined method Sofa\Revisionable\Laravel\ServiceProvider::publishes()

Did I forget something before run it?

**Comment by jarektkaczyk** [comment]
is it still a thing?

**Comment by kitsao** [comment]
I'm getting the same error.
