### ISSUE TITLE
Laravel 5.1 is not supported

### ISSUE THREAD

**Issue by itsneel** [jarektkaczyk/revisionable#65]
Not Really an issue, just wanted to know if this module supports Laravel 5.1 or not. As I am not able to integrate it with my Project (laravel 5.1.x)
v5.4 is not supported with L5.1
error is in serviceprovide.php line 144.

<img width="1185" alt="screen shot 2017-06-09 at 5 56 01 pm" src="https://user-images.githubusercontent.com/6545006/26975333-f2a92508-4d3c-11e7-8d44-9e3831a44060.png">

**Comment by jarektkaczyk** [comment]
that's true, no 5.1.
