### ISSUE TITLE
HTML field redered on revision->renderDiff()

### ISSUE THREAD

**Issue by barroca** [jarektkaczyk/revisionable#67]
Consider a field where you store html elements or any other text element. Consider that you stored a wrong html on it. The rederDiff() will present the diff to the browser as html to be parsed.

I discovered this issue modifying a text field into a html tag without closing it. That broke my layout.

**Comment by barroca** [comment]
The only way i could manage printing the data without parsing it was surrounding it with a ```<textarea readonly style="width: 100%">``` Tag. Maybe we could add a special kind of field that is printed as a urlencoded field.

**Comment by barroca** [comment]
hello, is it fixed or it won't be?

 Thanks

**Comment by jarektkaczyk** [comment]
@barroca issues is quite old, thus I closed it, but if it's still something to look into we can do it.

The only thing would be an example with code, because I'm not sure I understand the problem here?
