### ISSUE TITLE
Push Notifications

### ISSUE THREAD

**Issue by paramsinghvc** [jarektkaczyk/revisionable#7]
I want to build a notification system for my Laravel+AngularJS app for monitoring the changes happening in the system say "New Product has been added into the system". I'm using revisionable package for the same which keeps tracks of all the changes and updates in a table. Now I want to use websockets to implement Push Notifications but again I need to monitor that revisions table to fire notification on the events. How this can be achieved

**Comment by jarektkaczyk** [comment]
Not sure of what you need exactly, but off the top of my head I suggest custom `Listener` that will not only `log` the action in the revisions table, but also fire an event for your Push notifications.

On the other hand, why don't you do it in your models by adding similar funcitonality to what `Revisionable` does?
