### ISSUE TITLE
Error when generating the migration table

### ISSUE THREAD

**Issue by wrux** [jarektkaczyk/revisionable#71]
I've installed the package, added the provider in `app.php` and run the `php artisan vendor:publish[--provider="Sofa\Revisionable\Laravel\ServiceProvider"` task.

When I try to run `revisions:table` It just shows this error:

In BoundMethod.php line 135:
    Method Sofa\Revisionable\Laravel\RevisionsTableCommand::handle() does not exist

**Comment by jarektkaczyk** [comment]
Laravel changed the method call from `fire` to `handle`. 
Would be lovely if you can provide a PR with update :+1:

**Comment by sbreiler** [comment]
Are you gonna accept my PR? Anything wrong with it?
