### ISSUE TITLE
Ldap connection

### ISSUE THREAD

**Issue by subdesign** [jarektkaczyk/revisionable#72]
I use multiauth on my project, and the admins I want to revision are connected with LDAP. (Others with eloquent driver..)

'illuminate' provider could be used for that?

the package I use: https://github.com/SaschaDens/ldap-connector

thanks

**Comment by jarektkaczyk** [comment]
My guess is you'd need a custom providerr, unless `illuminate` works for you.
PR welcome! :+1:
