### ISSUE TITLE
Binary field implicit conversion

### ISSUE THREAD

**Issue by priithansen** [jarektkaczyk/revisionable#8]
Would it be safe to use text field instead of binary fields for revisionable old and new columns?

With binary fields sql server gives an error about implicit conversion.

``` php
Next exception 'Illuminate\Database\QueryException' with message 'SQLSTATE[42000]: [Microsoft][SQL Server Native Client 11.0][SQL Server]
Implicit conversion from data type nvarchar to varbinary(max) is not allowed. 
Use the CONVERT function to run this query. 
(SQL: insert into [revisions] (...
```

I'm quessing this is yet another place where sql server is more strict in its default config then mysql.

**Comment by jarektkaczyk** [comment]
BLOB is used here to avoid possible encoding issues.
I'm not proficient in SqlServer but I suppose you can safely change it to `nvarchar(max)`.

Let me know if you experience anything unexpected then.

**Comment by priithansen** [comment]
Seemed to work just ok with nvarchar too. But tested records where mostly relation id's to other tables so likely not a very conclusive test.
